### ISSUE TITLE
My new roomSense IQ doesn't boot up

### ISSUE THREAD

**Issue by ranveerkumar** [roomsense/roomsense-iq#3]
My RoomSense IQ's Wifi AP Name is not shown, and its also not connect to my home network (completed this step earlier). I tried updating the firmware although and then it is sitting silent after that.
The board keep showing me a very dim red light (with no blink or any other activity).

How can I debug and/or hard reset or install the latest firmware? Or should I assume the board has gone bad?

**Comment by geiseri** [comment]
Make sure it's getting enough power.  My laptop couldn't power it, but a 5v 2.4A wallwort worked just fine.
