### ISSUE TITLE
sightsense dashboard does not show 'occupied'

### ISSUE THREAD

**Issue by trentbrown13** [roomsense/roomsense-iq#4]
I am using the latest firmware (or I hope so, it would be nice to be able to see the current running firmware in Settings) - https://github.com/roomsense/firmware/blob/main/latest/roomsense-web20240903.bin

but the occupied/Unoccupied icon does not change when there is movement in the room. The movement icon does change from grey to red when it detects movement.

The occupied/unoccupied icon worked with another board I have but is now defunct - I will add another ticket for that
thanks!
-trent

**Comment by roomsense** [comment]
Hello

- You should be able to see the version on the SightSense setting page.
- The occupancy icon changes only if the device is connected to HA mqtt broker. Could you confirm if it is connected?

**Comment by trentbrown13** [comment]
Thanks, I found the version string. I had an earlier version on another roomsensor and the occupancy icon changed w/o being connectd to HA, I'll setup HA and give it another try
